# This file is distributed under the same license as the Django package.
#
# Translators:
# Bedilbek Khamidov <bedilbek@gmail.com>, 2019
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-05-18 11:26+0500\n"
"PO-Revision-Date: 2019-12-29 16:31+0000\n"
"Last-Translator: Bedilbek Khamidov <bedilbek@gmail.com>\n"
"Language-Team: Uzbek (http://www.transifex.com/django/django/language/uz/)\n"
"Language: uz\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: env/lib/python3.8/site-packages/django/contrib/auth/admin.py:46
msgid "Personal info"
msgstr "Shaxsiy ma'lumotlar"

#: env/lib/python3.8/site-packages/django/contrib/auth/admin.py:47
msgid "Permissions"
msgstr "Ruhsatnomalar"

#: env/lib/python3.8/site-packages/django/contrib/auth/admin.py:50
msgid "Important dates"
msgstr "Muhim sanalar"

#: env/lib/python3.8/site-packages/django/contrib/auth/admin.py:134
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr "%(key)r asosiy kalitli %(name)s obyekt mavjud emas"

#: env/lib/python3.8/site-packages/django/contrib/auth/admin.py:144
msgid "Password changed successfully."
msgstr "Parol muvaffaqiyatli o'zgartirildi."

#: env/lib/python3.8/site-packages/django/contrib/auth/admin.py:164
#, python-format
msgid "Change password: %s"
msgstr "Parolni o'zgartirish: %s"

#: env/lib/python3.8/site-packages/django/contrib/auth/apps.py:16
msgid "Authentication and Authorization"
msgstr "Autentifikatsiya va Avtorizatsiya"

#: env/lib/python3.8/site-packages/django/contrib/auth/base_user.py:48
msgid "password"
msgstr "parol"

#: env/lib/python3.8/site-packages/django/contrib/auth/base_user.py:49
msgid "last login"
msgstr "oxirgi kirish"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:41
msgid "No password set."
msgstr "Hech qanday parol qo'yilmagan."

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:46
msgid "Invalid password format or unknown hashing algorithm."
msgstr "Noto'g'ri parol formati yoki noma'lum heshlash algoritmi ishlatilgan."

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:84
#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:325
#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:398
msgid "The two password fields didn’t match."
msgstr "Ikkala parol maydoni bir-biriga mos kelmadi."

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:87
#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:140
#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:170
#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:402
msgid "Password"
msgstr "Parol"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:93
msgid "Password confirmation"
msgstr "Parolni tasdiqlash"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:96
#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:411
msgid "Enter the same password as before, for verification."
msgstr "Tekshirish uchun avvalgi parolni kiriting.."

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:142
msgid ""
"Raw passwords are not stored, so there is no way to see this user’s "
"password, but you can change the password using <a href=\"{}\">this form</a>."
msgstr ""
"Xom parollar saqlanmaydi, shuning uchun bu foydanaluvchining parolini "
"ko'rishni iloji yo'q, lekin siz <a href=\"{}\"> shu formadan </a> foydalanib "
"parolni o'zgartirishingiz mumkin. "

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:177
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"Iltimos, to'g'ri %(username)s va parolni kiriting. Ahamiyat bering, ikkala "
"maydonlar ham katta-kichik harfga sezgir bo'lishi mumkin."

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:180
msgid "This account is inactive."
msgstr "Bu akkaunt nofaol"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:243
msgid "Email"
msgstr "Elektron pochta"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:328
msgid "New password"
msgstr "Yangi parol"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:334
msgid "New password confirmation"
msgstr "Yangi parolni tasdiqlash"

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:370
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr ""
"Sizning eski parolingiz noto'g'ri kiritilgan edi. Iltimos, qaytadan kiriting."

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:373
msgid "Old password"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/forms.py:408
msgid "Password (again)"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:302
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:393
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:482
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:573
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:623
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:664
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:712
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:757
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:805
msgid "algorithm"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:303
msgid "iterations"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:304
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:399
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:484
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:577
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:624
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:665
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:806
msgid "salt"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:305
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:400
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:578
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:625
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:666
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:713
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:758
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:807
msgid "hash"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:394
msgid "variety"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:395
msgid "version"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:396
msgid "memory cost"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:397
msgid "time cost"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:398
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:576
msgid "parallelism"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:483
#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:574
msgid "work factor"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:485
msgid "checksum"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/hashers.py:575
msgid "block size"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:58
#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:109
msgid "name"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:62
msgid "content type"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:64
msgid "codename"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:69
msgid "permission"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:70
#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:112
msgid "permissions"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:119
msgid "group"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:120
#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:247
msgid "groups"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:238
msgid "superuser status"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:241
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:250
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:258
msgid "user permissions"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:260
msgid "Specific permissions for this user."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:331
msgid "username"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:334
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:337
msgid "A user with that username already exists."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:340
msgid "first name"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:341
msgid "last name"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:342
msgid "email address"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:344
msgid "staff status"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:346
msgid "Designates whether the user can log into this admin site."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:349
msgid "active"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:352
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:356
msgid "date joined"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:365
msgid "user"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/models.py:366
msgid "users"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:102
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:112
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:187
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:193
msgid "Your password can’t be too similar to your other personal information."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:224
msgid "This password is too common."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:229
msgid "Your password can’t be a commonly used password."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:239
msgid "This password is entirely numeric."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:244
msgid "Your password can’t be entirely numeric."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/templates/registration/password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/validators.py:12
msgid ""
"Enter a valid username. This value may contain only English letters, "
"numbers, and @/./+/-/_ characters."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:164
msgid "Logged out"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:221
msgid "Password reset"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:248
msgid "Password reset sent"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:258
msgid "Enter new password"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:321
msgid "Password reset unsuccessful"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:329
msgid "Password reset complete"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:341
msgid "Password change"
msgstr ""

#: env/lib/python3.8/site-packages/django/contrib/auth/views.py:364
msgid "Password change successful"
msgstr ""
